# Based on http://conda.pydata.org/docs/travis.html
language: minimal
sudo: false # use container based build
notifications:
  email: false

matrix:
  fast_finish: true
  include:
  - env: CONDA_ENV=3.6
  - env: CONDA_ENV=3.7

before_install:
  - set -e
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
  - conda info -a

install:
  - conda env create -n test_env --file ci/environment-dev-$CONDA_ENV.yml
  # extra test dependencies
  - conda install -c conda-forge pathlib nbconvert nbformat jupyter_client ipykernel pycodestyle
  - source activate test_env
  - conda list
  - pip install --no-deps -e .

script:
  - which python
  - python --version
  - python -OO -c "import intake_stac"
  # run unit tests
  - pytest --verbose --junitxml=test-reports/junit.xml --cov=intake_stac --cov-config ci/.coveragerc --cov-report term-missing
  # test building docs
  - pushd make html
  # test code style
  - pycodestyle

after_success:
  - codecov
