name: intake-stac-dev
channels:
  - conda-forge
dependencies:
  - aiohttp
  - autopep8
  - black
  - boto3
  - codecov
  - coverage
  - dask
  - distributed
  - flake8
  - geopandas
  - ipykernel
  - ipywidgets
  - isort
  - make
  - nbsphinx
  - netcdf4
  - numpy
  - numpydoc
  - pandoc
  - pip
  - pre_commit
  - pytest
  - pytest-cov
  - pytest-icdiff
  - python=3.7
  - pytoml
  - pyyaml
  - rasterio
  - recommonmark
  - requests
  - scikit-image
  - sphinx-copybutton
  - sphinx_rtd_theme
  - sphinx>=1.6
  - xarray
  - pip:
      - git+https://github.com/intake/filesystem_spec.git
      - git+https://github.com/sat-utils/sat-stac.git
      - git+https://github.com/sat-utils/sat-search.git
      - git+https://github.com/intake/intake.git
      - git+https://github.com/intake/intake-xarray.git
      - git+https://github.com/intake/intake_geopandas.git
      - git+https://github.com/intake/intake-parquet.git
