# Intake GUI also requires jupyterlab extensions installed
# conda env create -f ci/environment-gui-3.7.yml
# conda activate intake-stac-gui
# pip install -e .
# jupyter labextension install @pyviz/jupyterlab_pyviz
name: intake-stac-gui
channels:
  - conda-forge
dependencies:
  - python =3.7
  - aiohttp
  - autopep8
  - black
  - boto3
  - codecov
  - coverage
  - dask
  - datashader
  - distributed
  - flake8
  - geopandas
  - geoviews
  - hvplot
  - intake
  - intake-geopandas
  - intake-parquet
  - intake-xarray
  - ipykernel
  - ipywidgets
  - isort
  - jupyterlab
  - make
  - matplotlib
  - nbsphinx
  - netcdf4
  - nodejs >=10.0.0
  - numpy
  - numpydoc
  - pandoc
  - panel
  - pip
  - pre_commit
  - pystac
  - pytest
  - pytest-cov
  - pytest-icdiff
  - pytoml
  - pyyaml
  - rasterio
  - rioxarray
  - recommonmark
  - requests
  - sat-search>=0.3
  - scikit-image
  - sphinx-copybutton
  - sphinx_rtd_theme
  - sphinx >=1.6
  - xarray
