name: intake-stac-dev
channels:
  - conda-forge
dependencies:
  - aiohttp
  - autopep8
  - black
  - boto3
  - codecov
  - coverage
  - dask
  - distributed
  - flake8
  - geopandas
  - intake
  - intake-geopandas
  - intake-parquet
  - intake-xarray=0.3.1
  - ipykernel
  - ipywidgets
  - isort
  - make
  - nbsphinx
  - netcdf4
  - numpy
  - numpydoc
  - pandoc
  - pip
  - pre_commit
  - pytest
  - pytest-cov
  - pytest-icdiff
  - python=3.8
  - pytoml
  - pyyaml
  - rasterio
  - recommonmark
  - requests
  - sat-search>=0.3
  - sat-stac
  - scikit-image
  - sphinx-copybutton
  - sphinx_rtd_theme
  - sphinx>=1.6
  - xarray
