name: intake-stac-dev
channels:
  - conda-forge
dependencies:
  - autopep8
  - black
  - boto3
  - codecov
  - coverage
  - dask
  - distributed
  - flake8
  - intake
  - intake-xarray
  - ipykernel
  - isort
  - make
  - nbsphinx
  - netcdf4
  - numpy
  - numpydoc
  - pandoc
  - pip
  - pre_commit
  - pytest
  - pytest-cov
  - pytest-icdiff
  - python=3.6
  - pytoml
  - pyyaml
  - recommonmark
#  - sat-search
  - sat-stac
  - scikit-image
  - sphinx_rtd_theme
  - sphinx>=1.6
  - xarray
  - rasterio
  - ipywidgets
  - geopandas
  - pip:
    - git+https://github.com/sat-utils/sat-search.git
    - sphinx_copybutton
