name: intake-stac-dev
channels:
  - conda-forge
dependencies:
  - aiohttp
  - autopep8
  - black
  - boto3
  - codecov
  - coverage
  - dask
  - distributed
  - flake8
  - geopandas
  - intake
  - intake-xarray
  - ipykernel
  - ipywidgets
  - isort
  - make
  - nbsphinx
  - netcdf4
  - numpy
  - numpydoc
  - pandoc
  - pip
  - pre_commit
  - pytest
  - pytest-cov
  - pytest-icdiff
  - python=3.6
  - pytoml
  - pyyaml
  - rasterio
  - recommonmark
  - requests
  - sat-stac
  - scikit-image
  - sphinx_rtd_theme
  - sphinx>=1.6
  - xarray
  - pip:
      - sat-search==0.3.0rc1
      - sphinx_copybutton
