name: intake-stac-dev
channels:
  - conda-forge
dependencies:
  - autopep8
  - black
  - codecov
  - coverage
  - dask
  - distributed
  - flake8
  - intake
  - intake-xarray
  - ipykernel
  - isort
  - make
  - nbsphinx
  - netcdf4
  - numpy
  - numpydoc
  - pandoc
  - pip
  - pre_commit
  - pytest
  - pytest-cov
  - pytest-icdiff
  - python=3.7
  - pytoml
  - pyyaml
  - recommonmark
  - sphinx_rtd_theme
  - sphinx>=1.6
  - xarray
  - rasterio
  - ipywidgets
  - pip:
    - sphinx_copybutton
    - sat-stac
    - git+https://github.com/intake/intake.git
